# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02354959903c56b0c0093a457d64356ed9459e9c6c2b50cd5361cbb16a14d2616bca18525760abe58f13ef28e94a713793b4ec3df4f7a7d3bd25d55823e678ab

test:
  secret_key_base: 323c377a93ad35626b5b71d066a048d543beae8a7346cc7ff7278c36865888bae4fbf2aca6a9aaaf22e58c66dd03d23a9f0a35ea0c6274662b719b0a5c4624b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
